# services:
#   api:
#     build: .
#     container_name: "api"
#     volumes:
#       - ./app:/app
#     ports:
#       - 8000:8000

services:
  app:
    build: .
    container_name: fastapi-application
    environment:
      PORT: 8000
    env_file:
      - .env
    volumes:
      - ./app:/app
    ports:
      - "8000:8000"
