# 
FROM python:3.12.3

# 
WORKDIR /app

# 
COPY ./requirements.txt .

# 
RUN pip3 install --no-cache-dir --upgrade -r /code/requirements.txt
RUN pip3 install --no-cache-dir "fastapi[standard]"

# 
COPY . .

# 
EXPOSE 8000